// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHcafHuqUUUIe2J_nIgH7XBLK5E-vvWr8',
    appId: '1:981601908583:web:f418f6aa52c5c4f97021c2',
    messagingSenderId: '981601908583',
    projectId: 'e-health-app-1312',
    authDomain: 'e-health-app-1312.firebaseapp.com',
    storageBucket: 'e-health-app-1312.appspot.com',
    measurementId: 'G-0HYKQN3WRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpwZXnnbeitrE72Tvd3mEzkNYcHzCsstY',
    appId: '1:981601908583:android:0f0c189089f9ddd17021c2',
    messagingSenderId: '981601908583',
    projectId: 'e-health-app-1312',
    storageBucket: 'e-health-app-1312.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD10wX7xwRcfxL7Jg6HLFghd7nDk75V5fk',
    appId: '1:981601908583:ios:535b15562d3523187021c2',
    messagingSenderId: '981601908583',
    projectId: 'e-health-app-1312',
    storageBucket: 'e-health-app-1312.appspot.com',
    iosClientId: '981601908583-edsk0huanfoo0m4tghspf4si28e7tsbt.apps.googleusercontent.com',
    iosBundleId: 'com.example.eHealthProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD10wX7xwRcfxL7Jg6HLFghd7nDk75V5fk',
    appId: '1:981601908583:ios:535b15562d3523187021c2',
    messagingSenderId: '981601908583',
    projectId: 'e-health-app-1312',
    storageBucket: 'e-health-app-1312.appspot.com',
    iosClientId: '981601908583-edsk0huanfoo0m4tghspf4si28e7tsbt.apps.googleusercontent.com',
    iosBundleId: 'com.example.eHealthProject',
  );
}
